org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric Properties - https://fabricmc.net/develop
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
# The full version is <minecraft_version>.<mod_version>, composed in build.gradle.
mod_version=0.1
group=com.overhaul
archives_base_name=overhaul

# Dependencies
fabric_api_version=0.158.0+26.2
